from __future__ import annotations


def sample_grocery_order_item_records() -> list[dict[str, object]]:
    return [
        _record(
            shop="kosik",
            order_id="kosik-demo-2026-01-15",
            order_date="2026-01-15",
            order_item_id="kosik-line-1",
            product_id="milk-1l",
            product_name="Fresh milk 1L",
            brand="Farm Fresh",
            main_category="Dairy and eggs",
            category="Milk",
            quantity=2.0,
            unit="pcs",
            price_total=59.8,
            product_description="Sample milk product used for export format checks.",
            ingredients_text="Milk.",
        ),
        _record(
            shop="kosik",
            order_id="kosik-demo-2026-01-15",
            order_date="2026-01-15",
            order_item_id="kosik-line-2",
            product_id="oranges-1kg",
            product_name="Oranges",
            brand=None,
            main_category="Fruit and vegetables",
            category="Fruit",
            quantity=1.0,
            unit="kg",
            price_total=49.9,
            product_description="Sample seasonal fruit product.",
            ingredients_text=None,
        ),
        _record(
            shop="kosik",
            order_id="kosik-demo-2026-04-03",
            order_date="2026-04-03",
            order_item_id="kosik-line-3",
            product_id="eggs-10",
            product_name="Free range eggs 10 pcs",
            brand="Happy Farm",
            main_category="Dairy and eggs",
            category="Eggs",
            quantity=1.0,
            unit="pack",
            price_total=69.9,
            product_description="Sample eggs product used for seasonal basket examples.",
            ingredients_text="Eggs.",
        ),
        _record(
            shop="kosik",
            order_id="kosik-demo-2026-04-03",
            order_date="2026-04-03",
            order_item_id="kosik-line-4",
            product_id="flour-1kg",
            product_name="Plain flour 1kg",
            brand="Classic",
            main_category="Pantry",
            category="Baking",
            quantity=2.0,
            unit="pcs",
            price_total=45.8,
            product_description="Sample baking product.",
            ingredients_text="Wheat flour.",
        ),
        _record(
            shop="rohlik",
            order_id="rohlik-demo-900001",
            order_date="2026-06-12",
            order_item_id="rohlik-line-1",
            product_id="strawberries-500g",
            product_name="Strawberries 500g",
            brand="Seasonal",
            main_category="Fruit and vegetables",
            category="Fruit",
            quantity=2.0,
            unit="pack",
            price_total=159.8,
            product_description="Sample summer fruit product.",
            ingredients_text=None,
        ),
        _record(
            shop="rohlik",
            order_id="rohlik-demo-900001",
            order_date="2026-06-12",
            order_item_id="rohlik-line-2",
            product_id="sparkling-water-1-5l",
            product_name="Sparkling water 1.5L",
            brand="Aqua",
            main_category="Drinks",
            category="Water",
            quantity=6.0,
            unit="pcs",
            price_total=89.4,
            product_description="Sample drink product.",
            ingredients_text="Water, carbon dioxide.",
        ),
        _record(
            shop="rohlik",
            order_id="rohlik-demo-900145",
            order_date="2026-12-20",
            order_item_id="rohlik-line-3",
            product_id="butter-250g",
            product_name="Butter 250g",
            brand="Creamery",
            main_category="Dairy and eggs",
            category="Butter",
            quantity=2.0,
            unit="pcs",
            price_total=119.8,
            product_description="Sample winter baking product.",
            ingredients_text="Cream.",
        ),
        _record(
            shop="rohlik",
            order_id="rohlik-demo-900145",
            order_date="2026-12-20",
            order_item_id="rohlik-line-4",
            product_id="cinnamon-20g",
            product_name="Ground cinnamon 20g",
            brand="Spice House",
            main_category="Pantry",
            category="Spices",
            quantity=1.0,
            unit="pcs",
            price_total=24.9,
            product_description="Sample spice product.",
            ingredients_text="Cinnamon.",
        ),
    ]


def _record(
    shop: str,
    order_id: str,
    order_date: str,
    order_item_id: str,
    product_id: str,
    product_name: str,
    brand: str | None,
    main_category: str,
    category: str,
    quantity: float,
    unit: str,
    price_total: float,
    product_description: str,
    ingredients_text: str | None,
) -> dict[str, object]:
    unit_price = round(price_total / quantity, 2)
    category_path = [main_category] if main_category == category else [main_category, category]
    category_ids = [_slug(value) for value in category_path]

    return {
        "shop": shop,
        "order_id": order_id,
        "order_number": order_id,
        "order_date": order_date,
        "order_created_at": f"{order_date}T10:00:00+01:00",
        "delivery_slot_start": f"{order_date}T18:00:00+01:00",
        "delivery_slot_end": f"{order_date}T19:00:00+01:00",
        "order_item_id": order_item_id,
        "product_id": product_id,
        "product_slug": product_id,
        "product_url": f"/{product_id}",
        "product_name": product_name,
        "brand": brand,
        "main_category_id": category_ids[0],
        "main_category": main_category,
        "category_id": category_ids[-1],
        "category": category,
        "category_path": category_path,
        "category_ids": category_ids,
        "quantity": quantity,
        "quantity_ordered": quantity,
        "quantity_delivered": quantity,
        "unit": unit,
        "package_quantity": None,
        "package_unit": unit,
        "price_total": price_total,
        "price_unit": unit_price,
        "price_per_unit": unit_price,
        "price_per_unit_unit": unit,
        "currency": "CZK",
        "product_description": product_description,
        "ingredients_text": ingredients_text,
        "product_enriched": True,
    }


def _slug(value: str) -> str:
    return value.lower().replace(" and ", "-").replace(" ", "-")
